variables:
  - group: GitHub2StorageVars

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - dtmi/**

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
 - bash: az storage blob upload-batch -d '$web/dtmi' --account-name iotmodelsregistry -s dtmi --if-unmodified-since 2018-01-01T01:01:01Z --account-key $MAPPED_ACCESS_KEY
   displayName: Copy Models to Storage iotmodelsregistry
   env:
    MAPPED_ACCESS_KEY: $(IOTMODELS_ACCOUNT_KEY)
